server:
  port: 10000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/api/v3/api-docs/auth
          filters:
            - RewritePath=/api/v3/api-docs/auth, /v3/api-docs
        - id: route-service
          uri: lb://route
          predicates:
            - Path=/api/route/**
          filters:
            - StripPrefix=2
        - id: route-service-docs
          uri: lb://route
          predicates:
            - Path=/api/v3/api-docs/route
          filters:
            - RewritePath=/api/v3/api-docs/route, /v3/api-docs
        - id: destination-service
          uri: lb://destination
          predicates:
            - Path=/api/destination/**
          filters:
            - StripPrefix=2
        - id: destination-service-docs
          uri: lb://destination
          predicates:
            - Path=/api/v3/api-docs/destination
          filters:
            - RewritePath=/api/v3/api-docs/destination, /v3/api-docs
        - id: generic-service
          uri: lb://generic
          predicates:
            - Path=/api/generic/**
          filters:
            - StripPrefix=2
        - id: generic-service-docs
          uri: lb://generic
          predicates:
            - Path=/api/v3/api-docs/generic
          filters:
            - RewritePath=/api/v3/api-docs/generic, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service API
        url: /api/v3/api-docs/auth
      - name: Route Service API
        url: /api/v3/api-docs/route
      - name: Destination Service API
        url: /api/v3/api-docs/destination
      - name: Generic Service API
        url: /api/v3/api-docs/generic

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info
